### ISSUE TITLE
compile failure w/ base < 4.5

### ISSUE THREAD

**Issue by hvr** [ekmett/ansi-wl-pprint#13]
I just revised https://hackage.haskell.org/package/ansi-wl-pprint-0.6.8/revisions/ because

```
Configuring ansi-wl-pprint-0.6.8...
Preprocessing library for ansi-wl-pprint-0.6.8..
Building library for ansi-wl-pprint-0.6.8..
[1 of 2] Compiling Text.PrettyPrint.ANSI.Leijen.Internal ( Text/PrettyPrint/ANSI/Leijen/Internal.hs, dist/build/Text/PrettyPrint/ANSI/Leijen/Internal.o )
[2 of 2] Compiling Text.PrettyPrint.ANSI.Leijen ( Text/PrettyPrint/ANSI/Leijen.hs, dist/build/Text/PrettyPrint/ANSI/Leijen.o )

Text/PrettyPrint/ANSI/Leijen.hs:169:10:
    The fixity signature for `<>' lacks an accompanying binding
      (You cannot give a fixity signature for an imported value)
cabal: Failed to build ansi-wl-pprint-0.6.8
```

And in fact, Travis CI only tests back to GHC 7.4.2

**Comment by quchen** [comment]
I recently removed CI for 7.0 and 7.2 since I see no need to maintain them anymore. Should I? Or is the issue just about fixing the constraint in the code?

**Comment by hvr** [comment]
@quchen Well, the point of using various GHC releases is (also) about validating the version bounds for `base`. So if you don't test with GHC 7.0, you have no empiric justification to claim compatibility with `base == 4.3.*`. And it's totally ok to decide not to support GHC 7.0, and set the lower bound on `base` accordingly to signal the supported range (not the least, so you avoid me or others filing bugs about it ;-) ).

**Comment by quchen** [comment]
That makes sense, I should have been more careful about this.
