### ISSUE TITLE
Release with bumped ansi-terminal bound

### ISSUE THREAD

**Issue by quchen** [ekmett/ansi-wl-pprint#15]
#14 increased the upper version bound of `ansi-terminal`; @TomMD requested a new release in [a code comment](https://github.com/ekmett/ansi-wl-pprint/commit/2914bbb76d8bf81f4ed54b5ab0019b8c71b84c24).

@hvr, before I do it – revision or patch level bump? :-)

**Comment by hvr** [comment]
@quchen Sorry, only noticed this now: this is clearly a revision (assuming that upgrading to ansi-terminal-0.8 doesn't change the semantics/exports of ansi-wl-pprint's API). 

As a general rule of thumb, if it's a version bound relaxation that according to the PVP would *not* require a major or minor version bump, a revision shall be used.

PS: here's the edit link for convenience: http://hackage.haskell.org/package/ansi-wl-pprint-0.6.8.1/ansi-wl-pprint.cabal/edit

**Comment by RyanGlScott** [comment]
Ping @quchen. Can you bump the upper version bounds on Hackage?

**Comment by phadej** [comment]
I was bold and went ahead and made a revision http://hackage.haskell.org/package/ansi-wl-pprint-0.6.8.1/revisions/

**Comment by hvr** [comment]
Let's close this then
