### ISSUE TITLE
Mark as "deprecated" on Hackage

### ISSUE THREAD

**Issue by taktoa** [ekmett/ansi-wl-pprint#18]
Now that [`prettyprinter`](https://hackage.haskell.org/package/prettyprinter) is out and relatively stable, perhaps it would be best to direct would-be users of `ansi-wl-pprint` to that library instead, since at least IMO it represents a more modern approach. AFAICT this wouldn't break anyone's code; it would just discourage newbies from using `ansi-wl-pprint`.

Tagging @quchen in case he intends to make breaking changes to `prettyprinter` and in case there are any issues with `prettyprinter` that prevent it from being a full-featured replacement for `ansi-wl-pprint`.

(also, I think this should go without saying, but I'm not trying to shit on `ansi-wl-pprint` or any of the work its maintainers have done, I think it is a relatively well-engineered library that has served the Haskell ecosystem well)

**Comment by hvr** [comment]
This seems to imply that there should be only one library for any given task...? This is like saying that `test-framework` ought to be deprecated in favour of `tasty`; or that `parsec` should be deprecated in favour of `megaparsec`, etc... (which I'd disagree with) :-)

**Comment by taktoa** [comment]
Well, in the case of `test-framework` versus `tasty` I'd agree that deprecating `test-framework` would be silly, since they represent different approaches taken by different people, whereas `parsec` versus `megaparsec` is a better example, since `megaparsec` was forked from `parsec` IIRC, just as `prettyprinter` was forked from `ansi-wl-pprint`. However, since the dependency footprint of `megaparsec` is much larger than that of `parsec`, I'd argue that there's still a place for `parsec`, whereas `prettyprinter` + `prettyprinter-ansi-terminal` only depend on two more packages (`text` and `void`) than `ansi-wl-pprint`.

Also, I'm not suggesting that `ansi-wl-pprint` be _deleted_ or even that anyone should stop maintaining it, which is what would be implied by "there should be only one library for any given task". I think it's totally reasonable to say that "the Haskell community should try to agree on good defaults for any given task", unless there are a variety of approaches represented by the competing libraries. Is it really so controversial to claim that the API of `prettyprinter` is a strict improvement on that of `ansi-wl-pprint` so any code developed against the `ansi-wl-pprint` API is effectively legacy code?

If deprecating the library is too harsh, what about just putting something in the Cabal description that directs would-be users of `ansi-wl-pprint` to `prettyprinter`?

**Comment by hvr** [comment]
> what about just putting something in the Cabal description that directs would-be users of ansi-wl-pprint to prettyprinter?

That's *imho* better, unless @ekmett considers ansi-wl-pprint truly deprecated :-)

**Comment by quchen** [comment]
Just tuning in to say there are no breaking changes planned for Prettyprinter. The long term plan was pretty much making ansi-wl-pprint obsolete, but without any urgency. :-)

**Comment by phadej** [comment]
I wouldn't consider `ansi-wl-pprint` truly deprecated when `trifecta` is still using it. Maybe that's the change which can be still done for `trifecta-2`.

When `ansi-wl-pprint` is true "satellite" of Kmettosphere, then Edward can either deprecate this package, or transfer maintainership to someone who wants still to use `ansi-wl-pprint` over `prettyprinter`.

So the question is: is @ekmett ok with migrating his packages to `prettyprinter`

Also what @RyanGlScott thinks about, e.g. `criterion` depends on `ansi-wl-pprint`. See http://packdeps.haskellers.com/reverse/ansi-wl-pprint

**Comment by RyanGlScott** [comment]
It looks like there are two separate issues being discussed:

1. Whether we should hard-deprecate `ansi-wl-pprint` (using Hackage's mechanism for doing so).
2. Whether we should soft-deprecate `ansi-wl-pprint` by recommending the use of `prettyprinter`/`prettyprinter-ansi-terminal` instead.

I definitely wouldn't support going with option 1, as the dependency footprint alone would indicate that plenty of folks find this package useful (at least in the current day and age). Having never used `prettyprinter` myself, I can't really comment on option 2, but even if we don't outright endorse the use of `prettyprinter` over `ansi-wl-pprint`, perhaps it would be worthwhile to include a comparison of the two libraries in the `README` file.

**Comment by ekmett** [comment]
@phadej: I'm happy to take a patch that moves `trifecta` over to `prettyprinter`, so long as it doesn't unduly burden the folks who work on Idris. That said, I migrated _to_ `ansi-wl-pprint` in the first place from my own code to match the dependencies I already had. Since `criterion` was already using it, I was building it anyways.

**Comment by quchen** [comment]
FWIW porting Idris to Prettyprinter is fairly easy, I've done it a couple of time as a compatibility check. :-)

**Comment by phadej** [comment]
What's @RyanGlScott's opinion on porting criterion to use prettyprinter? I can make patches to it and trifecta.

**Comment by RyanGlScott** [comment]
I don't care too much about `criterion`'s choice of pretty-printing library. However, swapping out `ansi-wl-pprint` for `prettyprinter` in `criterion` isn't as simple as you make it out to be. The reason `criterion` uses `ansi-wl-pprint` in the first place is because it uses `optparse-applicative`'s [`footerDoc`](https://hackage.haskell.org/package/optparse-applicative-0.14.0.0/docs/Options-Applicative.html#v:footerDoc) function, which takes a `Maybe ansi-wl-pprint:Doc` as an argument. You'd need to patch `optparse-applicative` first before getting around to `criterion`.

**Comment by RyanGlScott** [comment]
Or, to put it another way: this plan is blocked on https://github.com/pcapriotti/optparse-applicative/issues/273.

**Comment by phadej** [comment]
The repository is now marked deprecated on Hackage.
