### ISSUE TITLE
Relax upper bound to accommodate `ansi-terminal-1.0`

### ISSUE THREAD

**Issue by mpilgrem** [ekmett/ansi-wl-pprint#29]
Although the `ansi-wl-pprint` package is marked as 'deprecated' on Hackage, it is still a dependency of `optparse-applicative` and I am hoping it is still maintained.

`ansi-terminal-1.0` was released today. I will raise a pull request.

**Comment by phadej** [comment]
FWIW https://github.com/pcapriotti/optparse-applicative/issues/273 is six years old issue. Nudge that one.

**Comment by phadej** [comment]
Done in #28, #29, #31
