### ISSUE TITLE
Operator <$> conflicts with Functor

### ISSUE THREAD

**Issue by spinda** [ekmett/ansi-wl-pprint#6]
Since the `<$>` from `Data.Functor` is now in `Prelude`, renaming `<$>` to something else would be helpful. One might also rename `<$$>` to match.

Something like `<#>` and `<##>`, maybe?

**Comment by spinda** [comment]
Oops, Functor, not Applicative.

**Comment by quchen** [comment]
Closing as »not enough supply or demand«, since nobody seemed to be interested for a year. Hiding `(<$>)` solves this issue well enough so that a breaking change seems disproportionate.
