### ISSUE TITLE
draft paper link is 404

### ISSUE THREAD

**Issue by lspitzner** [ekmett/ansi-wl-pprint#8]
in the haddock of `Text.PrettyPrint.ANSI.Leijen`

**Comment by quchen** [comment]
Currently working link: https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf

I’ll implement this once #10 is merged, otherwise I’ll have to fix the merge conflict.

**Comment by quchen** [comment]
The link works again, it seems the server had a temporary problem. As a drive-by change, I’ve made it http**s** in 52752a8a3040f5b9301b13dae192c2f4fc720179.
