### ISSUE TITLE
Add semigroup instance

### ISSUE THREAD

**Issue by phadej** [ekmett/ansi-wl-pprint#9]
There is an orphan in Trifecta, but I don't see any reason why it cannot be here.

Happy to do a PR (for both, `ansi-wl-pprint`, and `trifecta`).

**Comment by HuwCampbell** [comment]
There's already an instance for it in master, there just hasn't been a hackage release including it.

**Comment by HuwCampbell** [comment]
@ekmett with 8.2 coming out soon, I would like to ask if we could please get a release with this. As some projects which rely on it (like optparse) will not be able to be built without warnings.

**Comment by hvr** [comment]
@HuwCampbell iirc we didn't enable new Semigroup-related warnings in GHC 8.2 yet (albeit if it was up to me, I'd accelerate the semigroup proposal impl so we can have nice things earlier than 2020 ;-) ); that's planned for GHC 8.4 afaik

Notwithstanding, a new release would be a good idea ;-)

/cc @ekmett

**Comment by HuwCampbell** [comment]
Thanks @hvr

**Comment by quchen** [comment]
Closing this since the instance is in master.
